# Generated by Django 4.1.5 on 2023-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book-placeholder.jpeg', upload_to='books/'),
        ),
    ]
